In [1]:
import tensorflow as tf

In [2]:
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector=tf.constant([10,50])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 50])>

In [5]:
vector.ndim

1

In [6]:
matrix=tf.constant([[10,50,5],[20,100,8],[6,3,13]])
matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 10,  50,   5],
       [ 20, 100,   8],
       [  6,   3,  13]])>

In [7]:
matrix.ndim

2

In [8]:
another_matrix = tf.constant(
    [
        [[11., 22.], [33., 44.]],
        [[55., 66.], [77., 88.]],
        [[99., 100.], [110., 120.]]
    ],
    dtype=tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2, 2), dtype=float16, numpy=
array([[[ 11.,  22.],
        [ 33.,  44.]],

       [[ 55.,  66.],
        [ 77.,  88.]],

       [[ 99., 100.],
        [110., 120.]]], dtype=float16)>

In [9]:
changeable_variable=tf.Variable([10,30])
unchangeable_variable=tf.constant([22,44])
print(changeable_variable)
print(unchangeable_variable)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 30])>
tf.Tensor([22 44], shape=(2,), dtype=int32)


In [10]:
changeable_variable[1].assign(50)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 50])>

In [11]:
unchangeable_variable[0]

<tf.Tensor: shape=(), dtype=int32, numpy=22>

In [12]:
rand_gen=tf.random.set_seed(43)
rand_gen=tf.random.uniform(shape=[5])
print(rand_gen)

tf.Tensor([0.2733041 0.5020257 0.6628481 0.6473899 0.3857293], shape=(5,), dtype=float32)


In [13]:
rand_ge=tf.random.set_seed(43)
rand_ge=tf.random.uniform(shape=[5])
print(rand_ge)

tf.Tensor([0.2733041 0.5020257 0.6628481 0.6473899 0.3857293], shape=(5,), dtype=float32)


In [14]:
ran_ge=tf.random.Generator.from_seed(42)
ran_ge=ran_ge.normal(shape=(2,3))
ran_ge

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [15]:
rand_gen==rand_ge

<tf.Tensor: shape=(5,), dtype=bool, numpy=array([ True,  True,  True,  True,  True])>

In [16]:
def functionBs():
    a=tf.random.uniform(shape=[3])
    b=tf.random.uniform(shape=[3])
    return a,b
print(functionBs())

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.5168259 , 0.73396254, 0.39616835], dtype=float32)>, <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.37664938, 0.7430246 , 0.69035363], dtype=float32)>)


In [17]:
def function_variable():
    variable=tf.Variable([[1,2],[3,4],[5,6]])
    return variable
print(function_variable())
def function_const():
    constant_variable=tf.constant([[11,21],[31,41],[51,61]])
    return constant_variable
print(function_const())

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>
tf.Tensor(
[[11 21]
 [31 41]
 [51 61]], shape=(3, 2), dtype=int32)


In [18]:
def fun_Assig():
    change_variable=tf.Variable([[155,2],[35,4],[5,23]])
    check_var=change_variable[0,0]
    if(change_variable[0,0]==155):
        change_variable[0,0].assign(201)
        return change_variable
    return change_variable
print(fun_Assig())

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[201,   2],
       [ 35,   4],
       [  5,  23]])>


In [19]:
shu=tf.constant([
    [201,   2],
       [ 35,   4],
       [  5,  23]])
tf.random.shuffle(shu,seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 35,   4],
       [  5,  23],
       [201,   2]])>

In [20]:
#Generating a random number and the shuffle
gen_random=tf.random.Generator.from_seed([42])
gen_random=gen_random.uniform(shape=[3,3])
tf.random.shuffle(gen_random)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.1199472 , 0.609588  , 0.84381545],
       [0.8354591 , 0.9162973 , 0.49464953],
       [0.5211133 , 0.7119492 , 0.45645106]], dtype=float32)>

In [21]:
import numpy as np

In [22]:
data=np.arange(1,25,dtype=int)
data


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [23]:
A=tf.constant(data)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [24]:
A=tf.constant(data,shape=(6,2,2))
tf.random.shuffle(A)
#A=A.normal(shape=(3,4))
#A

<tf.Tensor: shape=(6, 2, 2), dtype=int32, numpy=
array([[[21, 22],
        [23, 24]],

       [[ 5,  6],
        [ 7,  8]],

       [[17, 18],
        [19, 20]],

       [[ 9, 10],
        [11, 12]],

       [[ 1,  2],
        [ 3,  4]],

       [[13, 14],
        [15, 16]]])>

In [25]:
def numfucntion():
    value=np.arange(40,100,dtype=np.int64)
    return value
print(numfucntion())

[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87
 88 89 90 91 92 93 94 95 96 97 98 99]


In [26]:
changeable_var=tf.constant(numfucntion(),shape=(2,3,10))
changeable_var

<tf.Tensor: shape=(2, 3, 10), dtype=int64, numpy=
array([[[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]], dtype=int64)>

In [27]:
tf.random.shuffle(changeable_var,seed=43)

<tf.Tensor: shape=(2, 3, 10), dtype=int64, numpy=
array([[[70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]]], dtype=int64)>

In [28]:
changeable_var.ndim

3

In [29]:
scalar=tf.constant(40,3)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [30]:
scalar.shape

TensorShape([])

In [31]:
tf.rank(scalar)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [32]:
vector=tf.constant([
    [1,2],[3,4],[4,5]
])
vector

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 5]])>

In [33]:
tf.shape(vector)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [34]:
tf.rank(vector)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [35]:
#here we can make some dimensions and then we will check some rank size

In [36]:
rank_4val=tf.zeros(shape=(2,3,4,5))
rank_4val

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
tf.shape(rank_4val)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [38]:
rank_4val.ndim

4

In [39]:
tf.rank(rank_4val)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [40]:
tf.size(rank_4val)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [41]:
print("There we can print the shapes:",tf.shape(rank_4val).numpy())
print("There we can print only all the axis:",rank_4val.ndim)
print("There we can print the rank:",tf.rank(rank_4val))
print("There we can print the size:",tf.size(rank_4val).numpy())

There we can print the shapes: [2 3 4 5]
There we can print only all the axis: 4
There we can print the rank: tf.Tensor(4, shape=(), dtype=int32)
There we can print the size: 120


In [42]:
var_list=[2,3,4,5,6]
var_list[2:]


[4, 5, 6]

In [43]:
var_list[:3]

[2, 3, 4]

In [44]:
rank_4val[:1,:3,:2]

<tf.Tensor: shape=(1, 3, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
#get the value from each index from array
rank_4val[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
rank2=tf.ones(shape=(2,5))
rank2

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [47]:
tf.rank(rank2).numpy()

2

In [48]:
rank2[1:,1:]

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 1., 1.]], dtype=float32)>

In [49]:
rank_2=tf.constant([[2,3],[5,6]])
rank_2,tf.rank(rank_2).numpy()

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[2, 3],
        [5, 6]])>,
 2)

In [50]:
#we get the last item of each row
rank_2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 6])>

In [51]:
#apply basic operation on tensor
const_val=tf.constant([[2,3],[9,3]],dtype=np.float32)
const_val,const_val+10,const_val-10,const_val

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 3.],
        [9., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[12., 13.],
        [19., 13.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[-8., -7.],
        [-1., -7.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 3.],
        [9., 3.]], dtype=float32)>)

In [52]:
tf.math.square(const_val)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  9.],
       [81.,  9.]], dtype=float32)>

In [53]:
tf.math.add(const_val,12)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 15.],
       [21., 15.]], dtype=float32)>

In [54]:
tf.math.sqrt(const_val)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.4142135, 1.7320508],
       [3.       , 1.7320508]], dtype=float32)>

In [55]:
#Main problem to multiple a matrix

In [56]:
#matrix1=tf.constant([[10,20],[30,40],[50,60]],dtype=np.int16)
matrix1=np.arange(1,19,dtype=np.float32)
matrix1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.], dtype=float32)

In [57]:
mat1=tf.constant(matrix1,shape=[3,6])
mat1

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.]], dtype=float32)>

In [58]:
matrix2=np.arange(20,38,dtype=np.float32)
matrix2

array([20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
       33., 34., 35., 36., 37.], dtype=float32)

In [59]:
mat2=tf.constant(matrix2,shape=[6,3])
mat2

<tf.Tensor: shape=(6, 3), dtype=float32, numpy=
array([[20., 21., 22.],
       [23., 24., 25.],
       [26., 27., 28.],
       [29., 30., 31.],
       [32., 33., 34.],
       [35., 36., 37.]], dtype=float32)>

In [60]:
mat_res=tf.matmul(mat1,mat2)
print(mat_res.numpy())

[[ 630.  651.  672.]
 [1620. 1677. 1734.]
 [2610. 2703. 2796.]]


In [61]:
#from here we can work with tensordot product

In [62]:
x=tf.constant([[2,3],[4,5],[4,5]])
y=tf.constant([[10,20,1],[30,40,1],[5,0,60]])
x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5],
        [4, 5]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[10, 20,  1],
        [30, 40,  1],
        [ 5,  0, 60]])>)

In [63]:
z=tf.matmul(tf.transpose(y),x)
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[160, 205],
       [200, 260],
       [246, 308]])>

In [64]:
u_res=tf.matmul(tf.transpose(x),y)
u_res

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[160, 200, 246],
       [205, 260, 308]])>

In [65]:
tf.transpose(u_res)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[160, 205],
       [200, 260],
       [246, 308]])>

In [66]:
# from here we can start aggeration in 

In [67]:
#/*
#1.find the minimum
#2.find the maximum
#3.find the mean
#4.find the sum
#*/

In [68]:
x_min=tf.constant([[10, 25],
       [230, 210],
       [2, 38]])
tf.math.reduce_min(x_min),tf.math.reduce_min(x_min,axis=1),tf.math.reduce_min(x_min,axis=0)

(<tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 10, 210,   2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 2, 25])>)

In [69]:
x_max=tf.constant([[10, 20,  1],
        [30, 40,  1],
        [ 5,  0, 60]])
tf.math.reduce_max(x_max),tf.math.reduce_max(x_max,axis=0),tf.math.reduce_max(x_max,axis=1)

(<tf.Tensor: shape=(), dtype=int32, numpy=60>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([30, 40, 60])>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([20, 40, 60])>)

In [70]:
x_mean=tf.constant([[22, 22],
        [24, 24]])
tf.math.reduce_mean(x_mean),tf.math.reduce_mean(x_mean,axis=0),tf.math.reduce_mean(x_mean,axis=1)

(<tf.Tensor: shape=(), dtype=int32, numpy=23>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([23, 23])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([22, 24])>)

In [71]:
x_addition=tf.constant([[1,1,1],[1,1,1]])
x_addition,tf.rank(x_addition)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 1, 1],
        [1, 1, 1]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [72]:
tf.math.reduce_sum(x_addition),tf.math.reduce_sum(x_addition,axis=0),tf.math.reduce_sum(x_addition,axis=1)

(<tf.Tensor: shape=(), dtype=int32, numpy=6>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 2])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3])>)

In [73]:
x_rand=tf.random.uniform(minval=0,maxval=50,shape=(6,2),dtype=tf.dtypes.int32,
    seed=42,)
x_rand,tf.math.reduce_min(x_rand),tf.math.reduce_max(x_rand),tf.math.reduce_mean(x_rand),tf.math.reduce_sum(x_rand)

(<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
 array([[45, 31],
        [11, 32],
        [26, 42],
        [14, 10],
        [20, 29],
        [ 9, 18]])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>,
 <tf.Tensor: shape=(), dtype=int32, numpy=45>,
 <tf.Tensor: shape=(), dtype=int32, numpy=23>,
 <tf.Tensor: shape=(), dtype=int32, numpy=287>)

In [74]:
print("random values:",x_rand)
print("Find the min:",tf.math.reduce_min(x_rand).numpy())
print("find the max:",tf.math.reduce_max(x_rand).numpy())
print("find the mean:",tf.math.reduce_mean(x_rand).numpy())
print("find the sum:",tf.math.reduce_sum(x_rand).numpy())

random values: tf.Tensor(
[[45 31]
 [11 32]
 [26 42]
 [14 10]
 [20 29]
 [ 9 18]], shape=(6, 2), dtype=int32)
Find the min: 9
find the max: 45
find the mean: 23
find the sum: 287


In [75]:
#variance and standard deviation

In [76]:
pip install tensorflow-probability

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [77]:
import tensorflow_probability as tfp

In [78]:
asd=tf.constant([[2,3,4],[7,8,9]])
tfp.stats.variance(asd)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([6, 6, 6])>

In [79]:
random_integers = np.random.randint(0, 100, size=50)  # Creates a 3x3 matrix of random integers between 0 and 99
random_integers

array([15, 51, 93, 79, 80, 96, 89, 36, 15, 51, 52, 18, 31, 10, 13, 50,  1,
        6, 62, 75, 47, 63, 89, 33, 93, 30, 26, 46, 34, 68, 78, 70, 12,  4,
        4, 49, 48, 48, 72,  3, 77, 17, 97, 17,  4, 31, 31, 75, 49, 55])

In [80]:
tfp.stats.variance(random_integers)

<tf.Tensor: shape=(), dtype=int32, numpy=841>

In [81]:
tf.math.reduce_std(tf.cast(random_integers,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.002766>

In [82]:
#from here we can check the argmax and argmin

In [90]:
x_ar=tf.random.uniform(shape=[50])
tf.random.shuffle(x_ar)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.78612185, 0.31726503, 0.1722914 , 0.70874476, 0.69730794,
       0.8416065 , 0.3849386 , 0.34626675, 0.61888254, 0.47211683,
       0.9020469 , 0.5086142 , 0.5376916 , 0.81251955, 0.6622436 ,
       0.907583  , 0.22822821, 0.2983551 , 0.0993638 , 0.8922945 ,
       0.8750814 , 0.683172  , 0.533355  , 0.9320179 , 0.75875485,
       0.02582145, 0.51633835, 0.8449364 , 0.09198201, 0.55836475,
       0.92458355, 0.8889388 , 0.23043036, 0.44789958, 0.7764789 ,
       0.93059886, 0.18766773, 0.71336627, 0.12807798, 0.01143825,
       0.18298864, 0.75429726, 0.5866393 , 0.6632829 , 0.4122008 ,
       0.20791376, 0.251804  , 0.68970263, 0.5797553 , 0.78124344],
      dtype=float32)>

In [91]:
tf.argmax(x_ar)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [95]:
x_ar[tf.argmax(x_ar).numpy()],x_ar[tf.argmin(x_ar).numpy()]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9320179>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.011438251>)

In [96]:
#squeezing and one-hot value

In [115]:
x_sq=tf.random.uniform(shape=[1,1,1,20])
x_sq

<tf.Tensor: shape=(1, 1, 1, 20), dtype=float32, numpy=
array([[[[0.19002962, 0.28850865, 0.19735968, 0.7204642 , 0.96737564,
          0.9398055 , 0.40330863, 0.07204032, 0.2816105 , 0.00199497,
          0.7772821 , 0.20449877, 0.1623416 , 0.8221327 , 0.9206803 ,
          0.6421261 , 0.26286733, 0.49289572, 0.40931606, 0.5631454 ]]]],
      dtype=float32)>

In [102]:
res=tf.squeeze(x_sq)
res

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.7965336 , 0.52598166, 0.9817879 , 0.06619346, 0.28833055,
       0.82715154, 0.5366701 , 0.02258646, 0.00983977, 0.6966177 ,
       0.51939607, 0.41669846, 0.00864089, 0.23936772, 0.5651661 ,
       0.5682931 , 0.3450929 , 0.54263484, 0.23034954, 0.40831494],
      dtype=float32)>

In [103]:
x_sq==res

<tf.Tensor: shape=(1, 1, 1, 20), dtype=bool, numpy=
array([[[[ True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True]]]])>

In [121]:
g=np.random.randint(1,50,size=50)
g

array([31,  2, 27,  7,  5, 28, 16, 48, 40, 18, 39, 48,  7, 44, 26, 28, 30,
        2, 31, 44, 13, 27, 31, 43, 24, 16, 28, 45, 42,  6, 33, 46,  4, 44,
       25,  7, 49, 25, 40, 17, 18, 21, 10, 20, 35, 49,  5, 29, 36,  1])

In [138]:
xv=tf.one_hot(g,depth=50,on_value=0,off_value=1)
xv

<tf.Tensor: shape=(50, 50), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 0, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 0, 1, ..., 1, 1, 1]])>

In [144]:
tf.squeeze(xv1)
xv1=tf.one_hot(g,depth=50,on_value="t",off_value="f")
xv1

<tf.Tensor: shape=(50, 50), dtype=string, numpy=
array([[b'f', b'f', b'f', ..., b'f', b'f', b'f'],
       [b'f', b'f', b't', ..., b'f', b'f', b'f'],
       [b'f', b'f', b'f', ..., b'f', b'f', b'f'],
       ...,
       [b'f', b'f', b'f', ..., b'f', b'f', b'f'],
       [b'f', b'f', b'f', ..., b'f', b'f', b'f'],
       [b'f', b't', b'f', ..., b'f', b'f', b'f']], dtype=object)>

In [145]:
p=tf.one_hot(tf.cast(res,dtype=tf.int32),depth=4)
p

<tf.Tensor: shape=(20, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)>

In [146]:
some_list=[1,2,3,4,5,6]
vs=tf.one_hot(some_list,depth=6)
vs

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [148]:
vsw=tf.one_hot(some_list,depth=6,on_value=3,off_value=5)
vsw

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[5, 3, 5, 5, 5, 5],
       [5, 5, 3, 5, 5, 5],
       [5, 5, 5, 3, 5, 5],
       [5, 5, 5, 5, 3, 5],
       [5, 5, 5, 5, 5, 3],
       [5, 5, 5, 5, 5, 5]])>